# local, dev, prod 공통 설정
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
    username: root
    password: JJJTeam
  thymeleaf:
    cache:  false
<<<<<<< HEAD
# 프로파일 설정법  run config에서 spring.profiles.active=name1
=======
#mybatis:
#  config-location: 

>>>>>>> 수진회원가입로그인만들브랜치생성
---

spring:
  config:
    activate:
      on-profile: sujin
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: name1


---
spring:
  config:
    activate:
      on-profile: name2