# local, dev, prod 공통 설정
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
    username: root
    password: JJJTeam
  thymeleaf:
    cache:  false
  servlet:
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 100MB
    
itemImgLocation: /Users/jincrates/projects/upload/shop/item # C:/shop/item
uploadPath: file:///Users/jincrates/projects/upload/shop/  #file:///C:/shop/
# 프로파일 설정법  run config에서 spring.profiles.active=name1


bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    jwtCookieName: bezkoder-jwt
    jwtRefreshCookieName: bezkoder-jwt-refresh


## App Properties
#  bezkoder.app.jwtSecret= bezKoderSecretKey
#  #bezkoder.app.jwtExpirationMs= 3600000
#  #bezkoder.app.jwtRefreshExpirationMs= 86400000
#
#  ## For test
#  bezkoder.app.jwtExpirationMs= 60000
#  bezkoder.app.jwtRefreshExpirationMs= 120000


---

spring:
  config:
    activate:
      on-profile: sujin
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: name1


---
spring:
  config:
    activate:
      on-profile: name2