# local, dev, prod 공통 설정
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
    username: root
    password: JJJTeam
  thymeleaf:
    cache:  false
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 100MB
  devtools:
    restart:
      enabled: true
# itemImgLocation: /Users/jincrates/projects/upload/shop/item # C:/shop/item
# uploadPath: file:///Users/jincrates/projects/upload/shop/  #file:///C:/shop/

#itemImgLocation: /Users/admin/projects/upload/shop/items # C:/item
#uploadPath: file:///Users/admin/projects/upload/shop/items  #file:///C:/shop/

itemImgLocation: /C:/upload/shop/items # C:/item
uploadPath: file:///C:/upload/shop/items  #file:///C:/shop/
# 프로파일 설정법  run config에서 spring.profiles.active=name1

logging:
  level:
    root: info
    com:
      jjjteam:
        jmarket: trace

---
logging:
 level:
  root: info

server:
  port: 8082
  
spring:
  config:
    activate:
      on-profile: sujin

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
            
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
    

---
logging:
  level:
    root: info
spring:
  config:
    activate:
      on-profile: jungho
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/JmarketJungHoTest


---
logging:
 level:
  root: info

server:
  port: 8083
  
spring:
  config:
    activate:
      on-profile: taekbu
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/board_jtb

