# local, dev, prod 공통 설정
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
    username: root
    password: JJJTeam
  thymeleaf:
    cache:  false
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

itemdtail: "test"
# 프로파일 설정법  run config에서 spring.profiles.active=name1

logging:
  level:
    root: info
    com:
      jjjteam:
        jmarket: trace

---
logging:
 level:
  root: info

server:
  port: 8082

spring:
  config:
    activate:
      on-profile: sujin
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/Jmarket
  servlet:
    multipart:
      max-file-size:  200MB
      max-request-size: 200MB


itemImgLocation: /Users/jeongsujin/shop/study/item
uploadPath=file: /Users/jeongsujin/shop/study   
---


logging:
  level:
    root: info
spring:
  config:
    activate:
      on-profile: jungho
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/JmarketJungHoTest


---
logging:
 level:
  root: info

server:
  port: 8083
  
spring:
  config:
    activate:
      on-profile: taekbu
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/board_jtb

