# local, dev, prod 공통 설정
server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio
    username: root
    password: 1234
  thymeleaf:
    cache:  false
# 프로파일 설정법  run config에서 spring.profiles.active=name1


bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    jwtCookieName: bezkoder-jwt
    jwtRefreshCookieName: bezkoder-jwt-refresh


## App Properties
#  bezkoder.app.jwtSecret= bezKoderSecretKey
#  #bezkoder.app.jwtExpirationMs= 3600000
#  #bezkoder.app.jwtRefreshExpirationMs= 86400000
#
#  ## For test
#  bezkoder.app.jwtExpirationMs= 60000
#  bezkoder.app.jwtRefreshExpirationMs= 120000


---
logging:
 level:
  root: debug
 
spring:
  config:
    activate:
      on-profile: sujin

 

---

spring:
  config:
    activate:
      on-profile: name1


---
spring:
  config:
    activate:
      on-profile: name2