# local, dev, prod 공통 설정
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/JmarketJungHoTest
    username: root
    password: JJJTeam
  thymeleaf:
    cache:  false
# 프로파일 설정법  run config에서 spring.profiles.active=name1

logging:
#  file:
#    path: logs
  level:
    root: debug
    com:
      jjjteam:
        jmarket: trace
#    root: trace

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    jwtCookieName: bezkoder-jwt
    jwtRefreshCookieName: bezkoder-jwt-refresh


## App Properties
#  bezkoder.app.jwtSecret= bezKoderSecretKey
#  #bezkoder.app.jwtExpirationMs= 3600000
#  #bezkoder.app.jwtRefreshExpirationMs= 86400000
#
#  ## For test
#  bezkoder.app.jwtExpirationMs= 60000
#  bezkoder.app.jwtRefreshExpirationMs= 120000


---

spring:
  config:
    activate:
      on-profile: sujin
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: jungho
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://jjjteam.duckdns.org:3306/JmarketJungHoTest


---
spring:
  config:
    activate:
      on-profile: name2